FROM node:24.16

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Generate the Prisma client 
COPY tsconfig.json ./
COPY prisma ./prisma
RUN npx prisma generate

# Copy the reset of the source code
COPY src ./src

EXPOSE 3000

CMD [ "npm", "run", "dev" ]